export const ROUTES = {
  HOME:       '/',
  TOPICS:     '/topics',
  TOPIC:      '/topics/:topicId',
  VISUALIZER: '/visualizer/:type',
  INTERVIEW:  '/interview',
};

export const SUBTOPIC_ROUTES = {
  'dsa:Arrays':                  '/visualizer/array',
  'dsa:TwoPointers':             '/visualizer/array',
  'dsa:PrefixSum':               '/visualizer/array',
  'dsa:BinarySearch':            '/visualizer/array',
  'dsa:Matrices':                '/visualizer/matrix',
  'dsa:LinkedList':              '/visualizer/linkedlist',
  'dsa:Graphs':                  '/visualizer/graph',
  'dsa:Trees':                   '/visualizer/tree',
  'kafka:Partitions':            '/visualizer/kafka',
  'kafka:ISR':                   '/visualizer/kafka',
  'kafka:Consumer Groups':       '/visualizer/kafka',
  'kafka:Lag':                   '/visualizer/kafka',
  'java:JVM':                    '/visualizer/jvm',
  'java:GC':                     '/visualizer/jvm',
  'java:Threads':                '/visualizer/threads',
  'java:Locks':                  '/visualizer/threads',
  'kubernetes:Pods':             '/visualizer/kubernetes',
  'kubernetes:HPA':              '/visualizer/kubernetes',
  'kubernetes:Deployments':      '/visualizer/kubernetes',
  'kubernetes:Services':         '/visualizer/kubernetes',
  'system-design:Load Balancer': '/visualizer/systemdesign',
  'system-design:Cache':         '/visualizer/systemdesign',
  'system-design:CDN':           '/visualizer/systemdesign',
  'system-design:Raft':          '/visualizer/systemdesign',
  'system-design:Microservices': '/visualizer/systemdesign',
  'golang:Goroutines':           '/visualizer/golang',
  'golang:Channels':             '/visualizer/golang',
  'golang:Scheduler':            '/visualizer/golang',
  'golang:gRPC':                 '/visualizer/golang',
  'aws:Lambda':                  '/visualizer/aws',
  'aws:SQS':                     '/visualizer/aws',
  'aws:SNS':                     '/visualizer/aws',
  'aws:EKS':                     '/visualizer/aws',
  'aws:API Gateway':             '/visualizer/aws',
  'python:GIL':                  '/visualizer/python',
  'python:Async':                '/visualizer/python',
  'python:Decorators':           '/visualizer/python',
  'python:ML Pipelines':         '/visualizer/python',
  'dsa:Strings':                 '/visualizer/string',
  'dsa:HashMaps':                '/visualizer/hashmap',
  'dsa:Sets':                    '/visualizer/set',
  'sorting:Bubble Sort':         '/visualizer/sorting',
  'sorting:Merge Sort':          '/visualizer/sorting',
  'sorting:Quick Sort':          '/visualizer/sorting',
  'sorting:Heap Sort':           '/visualizer/sorting',
  'database:B-Tree':             '/visualizer/database',
  'database:Query Planning':     '/visualizer/database',
  'database:Transactions':       '/visualizer/database',
  'database:Joins':              '/visualizer/database',
  'redis:Data Types':            '/visualizer/redis',
  'redis:Pub/Sub':               '/visualizer/redis',
  'redis:Cluster':               '/visualizer/redis',
  'redis:Pipelining':            '/visualizer/redis',
  'docker:Image Layers':         '/visualizer/docker',
  'docker:Container Lifecycle':  '/visualizer/docker',
  'docker:Networking':           '/visualizer/docker',
  'docker:Compose':              '/visualizer/docker',
  'networking:TCP Handshake':    '/visualizer/networking',
  'networking:HTTP':             '/visualizer/networking',
  'networking:DNS':              '/visualizer/networking',
  'networking:Load Balancer':    '/visualizer/networking',
  'dp:Fibonacci':                '/visualizer/dp',
  'dp:Coin Change':              '/visualizer/dp',
  'dp:Knapsack':                 '/visualizer/dp',
  'dp:LCS':                      '/visualizer/dp',
  'dp:LIS':                      '/visualizer/dp',
};
