export const ROUTES = {
  HOME:       '/',
  TOPICS:     '/topics',
  TOPIC:      '/topics/:topicId',
  VISUALIZER: '/visualizer/:type',
  INTERVIEW:  '/interview',
};

export const SUBTOPIC_ROUTES = {
  'dsa:Arrays':                  '/visualizer/array',
  'dsa:Graphs':                  '/visualizer/graph',
  'dsa:Trees':                   '/visualizer/tree',
  'kafka:Partitions':            '/visualizer/kafka',
  'java:JVM':                    '/visualizer/jvm',
  'java:GC':                     '/visualizer/jvm',
  'java:Threads':                '/visualizer/threads',
  'kubernetes:Pods':             '/visualizer/kubernetes',
  'kubernetes:HPA':              '/visualizer/kubernetes',
  'kubernetes:Deployments':      '/visualizer/kubernetes',
  'system-design:Load Balancer': '/visualizer/systemdesign',
  'system-design:Cache':         '/visualizer/systemdesign',
  'system-design:CDN':           '/visualizer/systemdesign',
  'system-design:Raft':          '/visualizer/systemdesign',
  'golang:Goroutines':           '/visualizer/golang',
  'golang:Channels':             '/visualizer/golang',
  'golang:Scheduler':            '/visualizer/golang',
  'golang:gRPC':                 '/visualizer/golang',
  'aws:Lambda':                  '/visualizer/aws',
  'aws:SQS':                     '/visualizer/aws',
  'aws:EKS':                     '/visualizer/aws',
  'aws:API Gateway':             '/visualizer/aws',
};
