export const TOPICS = [
  {
    id: 'dsa',
    label: 'DSA',
    icon: '🧩',
    subtopics: ['Arrays', 'TwoPointers', 'BinarySearch', 'PrefixSum', 'Matrices', 'LinkedList', 'Graphs', 'Trees', 'DP', 'Strings', 'HashMaps', 'Sets'],
  },
  {
    id: 'java',
    label: 'Java',
    icon: '☕',
    subtopics: ['JVM', 'GC', 'Threads', 'Locks', 'Streams', 'Collections'],
  },
  {
    id: 'golang',
    label: 'Go',
    icon: '🐹',
    subtopics: ['Goroutines', 'Channels', 'Scheduler', 'gRPC'],
  },
  {
    id: 'python',
    label: 'Python',
    icon: '🐍',
    subtopics: ['Async', 'GIL', 'Decorators', 'ML Pipelines'],
  },
  {
    id: 'kubernetes',
    label: 'Kubernetes',
    icon: '☸️',
    subtopics: ['Pods', 'Deployments', 'Services', 'Ingress', 'HPA'],
  },
  {
    id: 'aws',
    label: 'AWS',
    icon: '☁️',
    subtopics: ['EC2', 'Lambda', 'SQS', 'SNS', 'EKS', 'API Gateway'],
  },
  {
    id: 'kafka',
    label: 'Kafka',
    icon: '📨',
    subtopics: ['Partitions', 'ISR', 'Consumer Groups', 'Lag'],
  },
  {
    id: 'system-design',
    label: 'System Design',
    icon: '🏗️',
    subtopics: ['Load Balancer', 'Cache', 'CDN', 'Microservices', 'Raft'],
  },
  {
    id: 'sorting',
    label: 'Sorting',
    icon: '📶',
    subtopics: ['Bubble Sort', 'Merge Sort', 'Quick Sort', 'Heap Sort'],
  },
  {
    id: 'database',
    label: 'Database',
    icon: '🗄️',
    subtopics: ['B-Tree', 'Query Planning', 'Transactions', 'Joins'],
  },
  {
    id: 'redis',
    label: 'Redis',
    icon: '🔴',
    subtopics: ['Data Types', 'Pub/Sub', 'Cluster', 'Pipelining'],
  },
  {
    id: 'docker',
    label: 'Docker',
    icon: '🐳',
    subtopics: ['Image Layers', 'Container Lifecycle', 'Networking', 'Compose'],
  },
  {
    id: 'networking',
    label: 'Networking',
    icon: '🌐',
    subtopics: ['TCP Handshake', 'HTTP', 'DNS', 'Load Balancer'],
  },
  {
    id: 'dp',
    label: 'Dynamic Programming',
    icon: '🧩',
    subtopics: ['Fibonacci', 'Coin Change', 'Knapsack', 'LCS', 'LIS', 'Edit Distance', 'House Robber', 'Palindrome Subseq'],
  },
];
