export const TOPIC_META = {
  dsa:            { color: 'blue',   desc: 'Arrays, Graphs, Trees, DP, Matrix, Strings with step-by-step simulation.' },
  java:           { color: 'yellow', desc: 'JVM internals, GC algorithms, thread lifecycle, locks, streams.' },
  golang:         { color: 'blue',   desc: 'Goroutines, channels, Go scheduler, gRPC patterns.' },
  python:         { color: 'green',  desc: 'Async I/O, GIL, decorators, ML pipelines.' },
  kubernetes:     { color: 'blue',   desc: 'Pod scheduling, HPA, rolling deployments, service mesh.' },
  aws:            { color: 'yellow', desc: 'EC2, Lambda, SQS, EKS, API Gateway architecture flows.' },
  kafka:          { color: 'red',    desc: 'Partitions, ISR, consumer groups, lag, leader election.' },
  'system-design':{ color: 'purple', desc: 'Load balancers, CDN, caching, Raft consensus, CAP theorem.' },
};

export const VISUALIZER_MAP = {
  'dsa:Arrays':                  'array',
  'dsa:Graphs':                  'graph',
  'dsa:Trees':                   'tree',
  'java:JVM':                    'jvm',
  'java:GC':                     'jvm',
  'java:Threads':                'threads',
  'java:Locks':                  'threads',
  'kafka:Partitions':            'kafka',
  'kafka:ISR':                   'kafka',
  'kafka:Consumer Groups':       'kafka',
  'kafka:Lag':                   'kafka',
  'kubernetes:Pods':             'kubernetes',
  'kubernetes:HPA':              'kubernetes',
  'kubernetes:Deployments':      'kubernetes',
  'kubernetes:Services':         'kubernetes',
  'system-design:Load Balancer': 'systemdesign',
  'system-design:Cache':         'systemdesign',
  'system-design:CDN':           'systemdesign',
  'system-design:Raft':          'systemdesign',
  'system-design:Microservices': 'systemdesign',
  'golang:Goroutines':           'golang',
  'golang:Channels':             'golang',
  'golang:Scheduler':            'golang',
  'golang:gRPC':                 'golang',
  'aws:Lambda':                  'aws',
  'aws:SQS':                     'aws',
  'aws:SNS':                     'aws',
  'aws:EKS':                     'aws',
  'aws:API Gateway':             'aws',
  'python:GIL':                  'python',
  'python:Async':                'python',
  'python:Decorators':           'python',
  'python:ML Pipelines':         'python',
};
