export const TOPIC_META = {
  dsa:            { color: 'blue',   desc: 'Arrays, Graphs, Trees, DP, Matrix, LinkedList, Strings with step-by-step simulation.' },
  java:           { color: 'yellow', desc: 'JVM internals, GC algorithms, thread lifecycle, locks, collections, classloader, string pool, HashMap treeification, volatile, exception stack unwinding.' },
  golang:         { color: 'blue',   desc: 'Goroutines, channels, Go scheduler, gRPC patterns.' },
  python:         { color: 'green',  desc: 'Async I/O, GIL, decorators, ML pipelines.' },
  kubernetes:     { color: 'blue',   desc: 'Pod scheduling, HPA, rolling deployments, Ingress, ConfigMaps, PV/PVC, DNS resolution, sidecar pattern, etcd Raft, node failure & eviction.' },
  aws:            { color: 'yellow', desc: 'EC2, Lambda, SQS, SNS, EKS, API Gateway, S3, IAM, Route53, ECS, Step Functions, Aurora/RDS, ElastiCache architecture flows.' },
  kafka:          { color: 'red',    desc: 'Partitions, ISR, consumer groups, lag, leader election.' },
  'system-design': { color: 'purple', desc: 'Uber ride-hailing, load balancers, CDN, caching, Raft consensus, CAP theorem.' },
  microservices:   { color: 'blue',   desc: 'Circuit breaker, service discovery, API gateway, event-driven architecture.' },
  sorting:        { color: 'blue',   desc: 'Bubble, merge, quick, heap sort with step-by-step comparison and swap tracking.' },
  database:       { color: 'yellow', desc: 'B-Tree indexing, SQL query plans, ACID transactions, join algorithms.' },
  redis:          { color: 'red',    desc: 'Data types, pub/sub channels, cluster hash slots, pipelining.' },
  docker:         { color: 'blue',   desc: 'Image layers, container lifecycle, bridge networking, docker-compose.' },
  networking:     { color: 'green',  desc: 'TCP handshake, HTTP/1 vs HTTP/2, DNS resolution, load balancer algorithms.' },
  os:             { color: 'purple', desc: 'CPU scheduling (FCFS, RR), paging & TLB, virtual memory & swap.' },
  ai:             { color: 'green',  desc: 'Transformer architecture, multi-head attention, word embeddings.' },
  distributed:    { color: 'blue',   desc: 'Raft consensus, CAP theorem, two-phase commit.' },
  concurrency:    { color: 'yellow', desc: 'Mutex lock/unlock, counting semaphores, producer-consumer with bounded buffer.' },
};

export const VISUALIZER_MAP = {
  'dsa:Arrays':                  'array',
  'dsa:TwoPointers':             'array',
  'dsa:PrefixSum':               'array',
  'dsa:BinarySearch':            'array',
  'dsa:Matrices':                'matrix',
  'dsa:LinkedList':              'linkedlist',
  'dsa:Graphs':                  'graph',
  'dsa:Trees':                   'tree',
  'java:JVM':                    'jvm',
  'java:GC':                     'jvm',
  'java:Threads':                'threads',
  'java:Locks':                  'threads',
  'java:Collections':            'java-collections',
  'java:Classloader':            'jvm',
  'java:String Pool':            'jvm',
  'java:HashMap Internals':      'jvm',
  'java:Volatile':               'jvm',
  'java:Exception Stack':        'jvm',
  'kafka:Partitions':            'kafka',
  'kafka:ISR':                   'kafka',
  'kafka:Consumer Groups':       'kafka',
  'kafka:Lag':                   'kafka',
  'kubernetes:Pods':             'kubernetes',
  'kubernetes:HPA':              'kubernetes',
  'kubernetes:Deployments':      'kubernetes',
  'kubernetes:Services':         'kubernetes',
  'kubernetes:Ingress':          'kubernetes',
  'kubernetes:Config & Storage': 'kubernetes',
  'kubernetes:DNS':              'kubernetes',
  'kubernetes:Sidecars':         'kubernetes',
  'kubernetes:etcd':             'kubernetes',
  'kubernetes:Node Failure':     'kubernetes',
  'system-design:Uber':              'uber',
  'microservices:Load Balancer':     'systemdesign',
  'microservices:Cache':             'systemdesign',
  'microservices:CDN':               'systemdesign',
  'microservices:Raft':              'systemdesign',
  'microservices:Circuit Breaker':   'microservices',
  'microservices:Service Discovery': 'microservices',
  'microservices:API Gateway':       'microservices',
  'microservices:Event-Driven':      'microservices',
  'golang:Goroutines':           'golang',
  'golang:Channels':             'golang',
  'golang:Scheduler':            'golang',
  'golang:gRPC':                 'golang',
  'aws:Lambda':                  'aws',
  'aws:SQS':                     'aws',
  'aws:SNS':                     'aws',
  'aws:EKS':                     'aws',
  'aws:API Gateway':             'aws',
  'aws:EC2':                     'aws',
  'aws:S3':                      'aws',
  'aws:IAM':                     'aws',
  'aws:Route53':                 'aws',
  'aws:ECS':                     'aws',
  'aws:Step Functions':          'aws',
  'aws:Aurora / RDS':             'aws',
  'aws:ElastiCache':              'aws',
  'python:GIL':                  'python',
  'python:Async':                'python',
  'python:Decorators':           'python',
  'python:ML Pipelines':         'python',
  'dsa:DP':                      'dp',
  'dsa:Strings':                 'string',
  'dsa:HashMaps':                'hashmap',
  'dsa:Sets':                    'set',
  'sorting:Bubble Sort':         'sorting',
  'sorting:Merge Sort':          'sorting',
  'sorting:Quick Sort':          'sorting',
  'sorting:Heap Sort':           'sorting',
  'database:B-Tree':             'database',
  'database:Query Planning':     'database',
  'database:Transactions':       'database',
  'database:Joins':              'database',
  'redis:Data Types':            'redis',
  'redis:Pub/Sub':               'redis',
  'redis:Cluster':               'redis',
  'redis:Pipelining':            'redis',
  'docker:Image Layers':         'docker',
  'docker:Container Lifecycle':  'docker',
  'docker:Networking':           'docker',
  'docker:Compose':              'docker',
  'networking:TCP Handshake':    'networking',
  'networking:HTTP':             'networking',
  'networking:DNS':              'networking',
  'networking:Load Balancer':    'networking',
  'os:Scheduler':                'os',
  'os:Paging':                   'os',
  'os:Virtual Memory':           'os',
  'ai:Transformer':              'ai',
  'ai:Attention':                'ai',
  'ai:Embeddings':               'ai',
  'distributed:Raft':            'distributed',
  'distributed:CAP Theorem':     'distributed',
  'distributed:2PC':             'distributed',
  'concurrency:Mutex':           'concurrency',
  'concurrency:Semaphore':       'concurrency',
  'concurrency:Producer-Consumer': 'concurrency',
};
