export const TOPIC_META = {
  dsa:            { color: 'blue',   desc: 'Arrays, Graphs, Trees, DP, Matrix, LinkedList, Strings with step-by-step simulation.' },
  java:           { color: 'yellow', desc: 'JVM internals, GC algorithms, thread lifecycle, locks, streams.' },
  golang:         { color: 'blue',   desc: 'Goroutines, channels, Go scheduler, gRPC patterns.' },
  python:         { color: 'green',  desc: 'Async I/O, GIL, decorators, ML pipelines.' },
  kubernetes:     { color: 'blue',   desc: 'Pod scheduling, HPA, rolling deployments, service mesh.' },
  aws:            { color: 'yellow', desc: 'EC2, Lambda, SQS, EKS, API Gateway architecture flows.' },
  kafka:          { color: 'red',    desc: 'Partitions, ISR, consumer groups, lag, leader election.' },
  'system-design':{ color: 'purple', desc: 'Load balancers, CDN, caching, Raft consensus, CAP theorem.' },
  sorting:        { color: 'blue',   desc: 'Bubble, merge, quick, heap sort with step-by-step comparison and swap tracking.' },
  database:       { color: 'yellow', desc: 'B-Tree indexing, SQL query plans, ACID transactions, join algorithms.' },
  redis:          { color: 'red',    desc: 'Data types, pub/sub channels, cluster hash slots, pipelining.' },
  docker:         { color: 'blue',   desc: 'Image layers, container lifecycle, bridge networking, docker-compose.' },
  networking:     { color: 'green',  desc: 'TCP handshake, HTTP/1 vs HTTP/2, DNS resolution, load balancer algorithms.' },
  dp:             { color: 'purple', desc: 'Fibonacci, Coin Change, 0/1 Knapsack, LCS, LIS with animated DP tables.' },
};

export const VISUALIZER_MAP = {
  'dsa:Arrays':                  'array',
  'dsa:TwoPointers':             'array',
  'dsa:PrefixSum':               'array',
  'dsa:BinarySearch':            'array',
  'dsa:Matrices':                'matrix',
  'dsa:LinkedList':              'linkedlist',
  'dsa:Graphs':                  'graph',
  'dsa:Trees':                   'tree',
  'java:JVM':                    'jvm',
  'java:GC':                     'jvm',
  'java:Threads':                'threads',
  'java:Locks':                  'threads',
  'kafka:Partitions':            'kafka',
  'kafka:ISR':                   'kafka',
  'kafka:Consumer Groups':       'kafka',
  'kafka:Lag':                   'kafka',
  'kubernetes:Pods':             'kubernetes',
  'kubernetes:HPA':              'kubernetes',
  'kubernetes:Deployments':      'kubernetes',
  'kubernetes:Services':         'kubernetes',
  'system-design:Load Balancer': 'systemdesign',
  'system-design:Cache':         'systemdesign',
  'system-design:CDN':           'systemdesign',
  'system-design:Raft':          'systemdesign',
  'system-design:Microservices': 'systemdesign',
  'golang:Goroutines':           'golang',
  'golang:Channels':             'golang',
  'golang:Scheduler':            'golang',
  'golang:gRPC':                 'golang',
  'aws:Lambda':                  'aws',
  'aws:SQS':                     'aws',
  'aws:SNS':                     'aws',
  'aws:EKS':                     'aws',
  'aws:API Gateway':             'aws',
  'python:GIL':                  'python',
  'python:Async':                'python',
  'python:Decorators':           'python',
  'python:ML Pipelines':         'python',
  'dsa:Strings':                 'string',
  'dsa:HashMaps':                'hashmap',
  'dsa:Sets':                    'set',
  'sorting:Bubble Sort':         'sorting',
  'sorting:Merge Sort':          'sorting',
  'sorting:Quick Sort':          'sorting',
  'sorting:Heap Sort':           'sorting',
  'database:B-Tree':             'database',
  'database:Query Planning':     'database',
  'database:Transactions':       'database',
  'database:Joins':              'database',
  'redis:Data Types':            'redis',
  'redis:Pub/Sub':               'redis',
  'redis:Cluster':               'redis',
  'redis:Pipelining':            'redis',
  'docker:Image Layers':         'docker',
  'docker:Container Lifecycle':  'docker',
  'docker:Networking':           'docker',
  'docker:Compose':              'docker',
  'networking:TCP Handshake':    'networking',
  'networking:HTTP':             'networking',
  'networking:DNS':              'networking',
  'networking:Load Balancer':    'networking',
  'dp:Fibonacci':                'dp',
  'dp:Coin Change':              'dp',
  'dp:Knapsack':                 'dp',
  'dp:LCS':                      'dp',
  'dp:LIS':                      'dp',
};
