export const TOPICS = [
  {
    id: 'dsa',
    label: 'DSA',
    icon: '🧩',
    subtopics: ['Arrays', 'TwoPointers', 'BinarySearch', 'PrefixSum', 'Matrices', 'LinkedList', 'Graphs', 'Trees', 'Trie', 'Union Find', 'Backtracking', 'DP', 'Strings', 'HashMaps', 'Sets', 'Bubble Sort', 'Merge Sort', 'Quick Sort', 'Heap Sort'],
  },
  {
    id: 'java',
    label: 'Java',
    icon: '☕',
    subtopics: ['JVM', 'GC', 'Threads', 'Locks', 'Streams', 'Collections', 'Classloader', 'String Pool', 'HashMap Internals', 'Volatile', 'Exception Stack'],
  },
  {
    id: 'spring',
    label: 'Spring',
    icon: '🍃',
    subtopics: ['IoC', 'MVC', 'AOP', 'Transactions', 'Security', 'JPA', 'AutoConfig', 'Cloud'],
  },
  {
    id: 'golang',
    label: 'Go',
    icon: '🐹',
    subtopics: ['Goroutines', 'Channels', 'Scheduler', 'gRPC'],
  },
  {
    id: 'python',
    label: 'Python',
    icon: '🐍',
    subtopics: ['Async', 'GIL', 'Decorators', 'ML Pipelines'],
  },
  {
    id: 'kubernetes',
    label: 'Kubernetes',
    icon: '☸️',
    subtopics: ['Pods', 'Deployments', 'Services', 'Ingress', 'HPA', 'Config & Storage', 'DNS', 'Sidecars', 'etcd', 'Node Failure'],
  },
  {
    id: 'aws',
    label: 'AWS',
    icon: '☁️',
    subtopics: ['EC2', 'Lambda', 'SQS', 'SNS', 'EKS', 'API Gateway', 'S3', 'IAM', 'Route53', 'ECS', 'Step Functions', 'Aurora / RDS', 'ElastiCache'],
  },
  {
    id: 'kafka',
    label: 'Kafka',
    icon: '📨',
    subtopics: ['Partitions', 'ISR', 'Consumer Groups', 'Lag'],
  },
  {
    id: 'system-design',
    label: 'System Design',
    icon: '🏗️',
    subtopics: ['Uber Request Flow', 'Uber Architecture', 'Uber Failure Modes', 'Load Balancer', 'Cache', 'CDN', 'Rate Limiter', 'Sharding', 'Replication', 'Message Queue', 'Raft Consensus'],
  },
  {
    id: 'microservices',
    label: 'Microservices',
    icon: '🔌',
    subtopics: ['Load Balancer', 'Cache', 'CDN', 'Raft', 'Circuit Breaker', 'Service Discovery', 'API Gateway', 'Event-Driven'],
  },
  {
    id: 'database',
    label: 'Database',
    icon: '🗄️',
    subtopics: ['B-Tree', 'Query Planning', 'Transactions', 'Joins'],
  },
  {
    id: 'redis',
    label: 'Redis',
    icon: '🔴',
    subtopics: ['Data Types', 'Pub/Sub', 'Cluster', 'Pipelining'],
  },
  {
    id: 'docker',
    label: 'Docker',
    icon: '🐳',
    subtopics: ['Image Layers', 'Container Lifecycle', 'Networking', 'Compose'],
  },
  {
    id: 'networking',
    label: 'Networking',
    icon: '🌐',
    subtopics: ['TCP Handshake', 'HTTP', 'DNS', 'Load Balancer'],
  },
  {
    id: 'os',
    label: 'Operating Systems',
    icon: '🖥️',
    subtopics: ['Scheduler', 'Paging', 'Virtual Memory'],
  },
  {
    id: 'ai',
    label: 'AI / Transformers',
    icon: '🤖',
    subtopics: ['Transformer', 'Attention', 'Embeddings'],
  },
  {
    id: 'distributed',
    label: 'Distributed Systems',
    icon: '🌍',
    subtopics: ['Raft', 'CAP Theorem', '2PC'],
  },
  {
    id: 'concurrency',
    label: 'Concurrency',
    icon: '🧵',
    subtopics: ['Mutex', 'Semaphore', 'Producer-Consumer'],
  },
];
