import type { KnowledgeNode, RelType, KnowledgeEdge } from './KnowledgeGraph'

export const DEFAULT_CONCEPT_GRAPH: KnowledgeNode[] = [
  { id: 'arrays', name: 'Arrays', description: 'Contiguous memory storage for ordered elements', category: 'data-structure', difficulty: 1, importance: 0.9, interviewFrequency: 0.9, prerequisites: [], relatedConcepts: ['linked-list', 'dynamic-array'], visualType: 'array' },
  { id: 'linked-list', name: 'Linked List', description: 'Sequential nodes with pointers to next/prev', category: 'data-structure', difficulty: 1, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['arrays'], relatedConcepts: ['arrays', 'hash-map'], visualType: 'graph' },
  { id: 'dynamic-array', name: 'Dynamic Array', description: 'Resizable array with amortized O(1) append', category: 'data-structure', difficulty: 1, importance: 0.8, interviewFrequency: 0.6, prerequisites: ['arrays'], relatedConcepts: ['linked-list'], visualType: 'array' },
  { id: 'hash-map', name: 'Hash Map', description: 'Key-value storage with O(1) average lookup', category: 'data-structure', difficulty: 2, importance: 0.9, interviewFrequency: 0.9, prerequisites: ['arrays'], relatedConcepts: ['hash-set', 'trie'], visualType: 'custom' },
  { id: 'hash-set', name: 'Hash Set', description: 'Unordered collection of unique elements', category: 'data-structure', difficulty: 2, importance: 0.7, interviewFrequency: 0.6, prerequisites: ['hash-map'], relatedConcepts: ['hash-map'], visualType: 'custom' },
  { id: 'heap', name: 'Heap', description: 'Tree-based priority queue with min/max property', category: 'data-structure', difficulty: 2, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['arrays', 'binary-tree'], relatedConcepts: ['priority-queue'], visualType: 'tree' },
  { id: 'stack', name: 'Stack', description: 'LIFO data structure with push/pop operations', category: 'data-structure', difficulty: 1, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['arrays'], relatedConcepts: ['queue'], visualType: 'array' },
  { id: 'queue', name: 'Queue', description: 'FIFO data structure with enqueue/dequeue', category: 'data-structure', difficulty: 1, importance: 0.7, interviewFrequency: 0.6, prerequisites: ['linked-list'], relatedConcepts: ['stack', 'deque'], visualType: 'array' },
  { id: 'binary-tree', name: 'Binary Tree', description: 'Tree where each node has at most 2 children', category: 'data-structure', difficulty: 2, importance: 0.8, interviewFrequency: 0.8, prerequisites: ['recursion'], relatedConcepts: ['bst', 'heap'], visualType: 'tree' },
  { id: 'bst', name: 'Binary Search Tree', description: 'Ordered tree with O(log n) search on average', category: 'data-structure', difficulty: 2, importance: 0.8, interviewFrequency: 0.8, prerequisites: ['binary-tree'], relatedConcepts: ['avl-tree', 'red-black-tree'], visualType: 'tree' },
  { id: 'trie', name: 'Trie', description: 'Tree structure for efficient string prefix matching', category: 'data-structure', difficulty: 3, importance: 0.5, interviewFrequency: 0.5, prerequisites: ['hash-map', 'tree-traversal'], relatedConcepts: ['hash-map'], visualType: 'tree' },
  { id: 'graph-ds', name: 'Graph (Data Structure)', description: 'Vertices and edges representing relationships', category: 'data-structure', difficulty: 2, importance: 0.8, interviewFrequency: 0.7, prerequisites: ['linked-list'], relatedConcepts: ['bfs', 'dfs'], visualType: 'graph' },

  { id: 'bubble-sort', name: 'Bubble Sort', description: 'Simple O(n²) sorting by adjacent swaps', category: 'algorithm', difficulty: 1, importance: 0.6, interviewFrequency: 0.5, prerequisites: ['arrays'], relatedConcepts: ['insertion-sort', 'selection-sort'], visualType: 'array', defaultAnimation: 'swap' },
  { id: 'insertion-sort', name: 'Insertion Sort', description: 'Builds sorted array one element at a time', category: 'algorithm', difficulty: 1, importance: 0.6, interviewFrequency: 0.5, prerequisites: ['arrays'], relatedConcepts: ['bubble-sort', 'selection-sort'], visualType: 'array', defaultAnimation: 'insert' },
  { id: 'selection-sort', name: 'Selection Sort', description: 'Repeatedly selects minimum element', category: 'algorithm', difficulty: 1, importance: 0.5, interviewFrequency: 0.4, prerequisites: ['arrays'], relatedConcepts: ['bubble-sort', 'insertion-sort'], visualType: 'array', defaultAnimation: 'select' },
  { id: 'quick-sort', name: 'Quick Sort', description: 'Divide-and-conquer O(n log n) sorting with pivot', category: 'algorithm', difficulty: 2, importance: 0.9, interviewFrequency: 0.9, prerequisites: ['arrays', 'recursion'], relatedConcepts: ['merge-sort', 'partitioning'], visualType: 'array', defaultAnimation: 'partition' },
  { id: 'merge-sort', name: 'Merge Sort', description: 'Stable O(n log n) divide-and-conquer sort', category: 'algorithm', difficulty: 2, importance: 0.8, interviewFrequency: 0.8, prerequisites: ['arrays', 'recursion'], relatedConcepts: ['quick-sort'], visualType: 'array', defaultAnimation: 'merge' },
  { id: 'binary-search', name: 'Binary Search', description: 'O(log n) search on sorted array', category: 'algorithm', difficulty: 1, importance: 0.9, interviewFrequency: 0.9, prerequisites: ['arrays', 'recursion'], relatedConcepts: ['bst'], visualType: 'array', defaultAnimation: 'search' },
  { id: 'dfs', name: 'Depth-First Search', description: 'Graph traversal exploring one branch fully before backtracking', category: 'algorithm', difficulty: 2, importance: 0.8, interviewFrequency: 0.8, prerequisites: ['graph-ds', 'recursion'], relatedConcepts: ['bfs', 'backtracking'], visualType: 'graph', defaultAnimation: 'traverse' },
  { id: 'bfs', name: 'Breadth-First Search', description: 'Graph traversal exploring neighbors level by level', category: 'algorithm', difficulty: 2, importance: 0.8, interviewFrequency: 0.8, prerequisites: ['graph-ds', 'queue'], relatedConcepts: ['dfs', 'shortest-path'], visualType: 'graph', defaultAnimation: 'traverse' },
  { id: 'dijkstra', name: "Dijkstra's Algorithm", description: 'Shortest path on weighted graphs', category: 'algorithm', difficulty: 3, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['bfs', 'heap'], relatedConcepts: ['a-star', 'bellman-ford'], visualType: 'graph' },
  { id: 'backtracking', name: 'Backtracking', description: 'Systematic trial-and-error for constraint satisfaction', category: 'algorithm', difficulty: 3, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['dfs', 'recursion'], relatedConcepts: ['n-queens', 'sudoku'], visualType: 'graph' },
  { id: 'two-pointers', name: 'Two Pointers', description: 'Technique using two indices to traverse arrays', category: 'algorithm', difficulty: 2, importance: 0.8, interviewFrequency: 0.8, prerequisites: ['arrays'], relatedConcepts: ['sliding-window'], visualType: 'array' },
  { id: 'sliding-window', name: 'Sliding Window', description: 'Technique for subarray/substring problems', category: 'algorithm', difficulty: 2, importance: 0.8, interviewFrequency: 0.8, prerequisites: ['two-pointers', 'hash-map'], relatedConcepts: ['two-pointers'], visualType: 'array' },
  { id: 'dynamic-programming', name: 'Dynamic Programming', description: 'Optimization by breaking into overlapping subproblems', category: 'algorithm', difficulty: 3, importance: 0.9, interviewFrequency: 0.9, prerequisites: ['recursion', 'memoization'], relatedConcepts: ['greedy-algorithms', 'divide-and-conquer'] },
  { id: 'recursion', name: 'Recursion', description: 'Function calling itself with smaller inputs', category: 'algorithm', difficulty: 1, importance: 0.9, interviewFrequency: 0.8, prerequisites: ['functions'], relatedConcepts: ['backtracking', 'dynamic-programming'] },
  { id: 'memoization', name: 'Memoization', description: 'Caching function results to avoid recomputation', category: 'algorithm', difficulty: 2, importance: 0.7, interviewFrequency: 0.6, prerequisites: ['recursion', 'hash-map'], relatedConcepts: ['dynamic-programming'] },
  { id: 'divide-and-conquer', name: 'Divide and Conquer', description: 'Split problem into independent subproblems', category: 'algorithm', difficulty: 2, importance: 0.7, interviewFrequency: 0.6, prerequisites: ['recursion'], relatedConcepts: ['merge-sort', 'quick-sort'] },
  { id: 'greedy-algorithms', name: 'Greedy Algorithms', description: 'Making locally optimal choices at each step', category: 'algorithm', difficulty: 2, importance: 0.6, interviewFrequency: 0.6, prerequisites: ['sorting'], relatedConcepts: ['dynamic-programming'] },
  { id: 'bit-manipulation', name: 'Bit Manipulation', description: 'Operations on individual bits for optimization', category: 'algorithm', difficulty: 2, importance: 0.6, interviewFrequency: 0.5, prerequisites: ['binary-numbers'], relatedConcepts: ['hashing'] },

  { id: 'kafka', name: 'Apache Kafka', description: 'Distributed event streaming platform', category: 'system-design', difficulty: 3, importance: 0.8, interviewFrequency: 0.7, prerequisites: ['publish-subscribe', 'distributed-systems'], relatedConcepts: ['raft', 'kafka-partitioning'], visualType: 'graph', defaultAnimation: 'flow' },
  { id: 'raft', name: 'Raft Consensus', description: 'Consensus algorithm for distributed systems', category: 'system-design', difficulty: 4, importance: 0.7, interviewFrequency: 0.6, prerequisites: ['distributed-systems', 'consensus-algorithms'], relatedConcepts: ['paxos', 'kafka'], visualType: 'graph', defaultAnimation: 'flow' },
  { id: 'load-balancing', name: 'Load Balancing', description: 'Distributing traffic across servers', category: 'system-design', difficulty: 2, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['distributed-systems'], relatedConcepts: ['reverse-proxy', 'consistent-hashing'] },
  { id: 'caching', name: 'Caching Strategies', description: 'Temporary storage for fast data retrieval', category: 'system-design', difficulty: 2, importance: 0.8, interviewFrequency: 0.8, prerequisites: ['hash-map'], relatedConcepts: ['redis', 'cdn', 'cache-eviction'], visualType: 'custom', defaultAnimation: 'flow' },
  { id: 'consistent-hashing', name: 'Consistent Hashing', description: 'Hash technique minimizing remapping on resizing', category: 'system-design', difficulty: 3, importance: 0.7, interviewFrequency: 0.6, prerequisites: ['hash-map', 'distributed-systems'], relatedConcepts: ['load-balancing', 'dht'] },
  { id: 'distributed-systems', name: 'Distributed Systems', description: 'Multiple nodes working together as one system', category: 'system-design', difficulty: 3, importance: 0.9, interviewFrequency: 0.8, prerequisites: ['networking-basics'], relatedConcepts: ['raft', 'cap-theorem', 'consensus-algorithms'] },
  { id: 'cap-theorem', name: 'CAP Theorem', description: 'Trade-off between Consistency, Availability, Partition tolerance', category: 'system-design', difficulty: 3, importance: 0.8, interviewFrequency: 0.7, prerequisites: ['distributed-systems'], relatedConcepts: ['eventual-consistency', 'paxos'] },
  { id: 'microservices', name: 'Microservices Architecture', description: 'Building applications as independent services', category: 'system-design', difficulty: 3, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['distributed-systems', 'api-design'], relatedConcepts: ['service-mesh', 'containerization'] },
  { id: 'api-design', name: 'API Design', description: 'Designing REST/GraphQL interfaces', category: 'system-design', difficulty: 2, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['http'], relatedConcepts: ['rest', 'graphql', 'grpc'] },
  { id: 'database-design', name: 'Database Design', description: 'Schema design, normalization, indexing', category: 'system-design', difficulty: 2, importance: 0.8, interviewFrequency: 0.8, prerequisites: ['sql-basics'], relatedConcepts: ['nosql', 'sharding', 'indexing'] },
  { id: 'sharding', name: 'Sharding', description: 'Horizontal partitioning of databases', category: 'system-design', difficulty: 3, importance: 0.7, interviewFrequency: 0.6, prerequisites: ['distributed-systems', 'database-design'], relatedConcepts: ['consistent-hashing', 'partitioning'] },
  { id: 'publish-subscribe', name: 'Pub/Sub Pattern', description: 'Messaging pattern with publishers and subscribers', category: 'system-design', difficulty: 2, importance: 0.7, interviewFrequency: 0.6, prerequisites: ['messaging-systems'], relatedConcepts: ['kafka', 'rabbitmq', 'event-driven'] },
  { id: 'reverse-proxy', name: 'Reverse Proxy', description: 'Server that forwards client requests to backend servers', category: 'system-design', difficulty: 2, importance: 0.6, interviewFrequency: 0.5, prerequisites: ['http', 'networking-basics'], relatedConcepts: ['load-balancing', 'nginx'] },

  { id: 'mutex', name: 'Mutex', description: 'Mutual exclusion lock for thread synchronization', category: 'concurrency', difficulty: 2, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['threads'], relatedConcepts: ['semaphore', 'spinlock'], visualType: 'graph', defaultAnimation: 'lock' },
  { id: 'deadlock', name: 'Deadlock', description: 'Circular wait where threads block indefinitely', category: 'concurrency', difficulty: 3, importance: 0.8, interviewFrequency: 0.8, prerequisites: ['mutex', 'threads'], relatedConcepts: ['deadlock-prevention', 'deadlock-detection'], visualType: 'graph', defaultAnimation: 'flow' },
  { id: 'race-condition', name: 'Race Condition', description: 'Unpredictable behavior from concurrent access', category: 'concurrency', difficulty: 3, importance: 0.8, interviewFrequency: 0.8, prerequisites: ['threads', 'mutex'], relatedConcepts: ['data-race', 'synchronization'], visualType: 'graph', defaultAnimation: 'flow' },
  { id: 'semaphore', name: 'Semaphore', description: 'Counter-based synchronization primitive', category: 'concurrency', difficulty: 2, importance: 0.6, interviewFrequency: 0.6, prerequisites: ['threads'], relatedConcepts: ['mutex', 'barrier'] },
  { id: 'threads', name: 'Threads', description: 'Lightweight processes sharing memory space', category: 'concurrency', difficulty: 2, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['os-processes'], relatedConcepts: ['mutex', 'race-condition', 'thread-pool'] },
  { id: 'thread-pool', name: 'Thread Pool', description: 'Reusable set of worker threads', category: 'concurrency', difficulty: 2, importance: 0.6, interviewFrequency: 0.5, prerequisites: ['threads'], relatedConcepts: ['executor-service'] },
  { id: 'synchronization', name: 'Synchronization', description: 'Coordinating access to shared resources', category: 'concurrency', difficulty: 2, importance: 0.7, interviewFrequency: 0.6, prerequisites: ['threads', 'mutex'], relatedConcepts: ['barrier', 'countdown-latch'] },
  { id: 'atomic-operations', name: 'Atomic Operations', description: 'Lock-free thread-safe operations', category: 'concurrency', difficulty: 3, importance: 0.6, interviewFrequency: 0.5, prerequisites: ['memory-model'], relatedConcepts: ['cas', 'lock-free-data-structures'] },

  { id: 'tcp-handshake', name: 'TCP 3-Way Handshake', description: 'SYN-SYN/ACK-ACK connection establishment', category: 'networking', difficulty: 2, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['tcp-ip'], relatedConcepts: ['tcp-flow-control', 'tcp-congestion'], visualType: 'graph', defaultAnimation: 'flow' },
  { id: 'http', name: 'HTTP Protocol', description: 'Hypertext Transfer Protocol for web communication', category: 'networking', difficulty: 1, importance: 0.8, interviewFrequency: 0.8, prerequisites: ['tcp-ip'], relatedConcepts: ['https', 'http2', 'rest'], visualType: 'graph', defaultAnimation: 'flow' },
  { id: 'dns', name: 'DNS Resolution', description: 'Domain name to IP address resolution', category: 'networking', difficulty: 2, importance: 0.7, interviewFrequency: 0.6, prerequisites: ['networking-basics'], relatedConcepts: ['cdn', 'load-balancing'] },
  { id: 'tcp-ip', name: 'TCP/IP Stack', description: 'Core internet protocol suite', category: 'networking', difficulty: 2, importance: 0.8, interviewFrequency: 0.7, prerequisites: ['networking-basics'], relatedConcepts: ['tcp-handshake', 'udp'] },
  { id: 'networking-basics', name: 'Networking Basics', description: 'IP addresses, ports, packets, routing fundamentals', category: 'networking', difficulty: 1, importance: 0.8, interviewFrequency: 0.7, prerequisites: ['computer-basics'], relatedConcepts: ['tcp-ip', 'dns'] },
  { id: 'cdn', name: 'Content Delivery Network', description: 'Distributed edge caching for content delivery', category: 'networking', difficulty: 2, importance: 0.6, interviewFrequency: 0.5, prerequisites: ['dns', 'caching'], relatedConcepts: ['load-balancing', 'edge-computing'] },

  { id: 'sql-basics', name: 'SQL Basics', description: 'Structured query language for relational databases', category: 'database', difficulty: 1, importance: 0.9, interviewFrequency: 0.9, prerequisites: ['database-design'], relatedConcepts: ['indexing', 'transactions'] },
  { id: 'indexing', name: 'Database Indexing', description: 'Data structure for fast query lookups', category: 'database', difficulty: 2, importance: 0.8, interviewFrequency: 0.8, prerequisites: ['sql-basics', 'bst'], relatedConcepts: ['b-tree', 'hash-index'] },
  { id: 'transactions', name: 'ACID Transactions', description: 'Atomic, Consistent, Isolated, Durable operations', category: 'database', difficulty: 3, importance: 0.8, interviewFrequency: 0.7, prerequisites: ['sql-basics', 'concurrency-basics'], relatedConcepts: ['isolation-levels', 'two-phase-commit'] },
  { id: 'nosql', name: 'NoSQL Databases', description: 'Non-relational database systems', category: 'database', difficulty: 2, importance: 0.7, interviewFrequency: 0.6, prerequisites: ['database-design'], relatedConcepts: ['mongodb', 'cassandra', 'cap-theorem'] },
  { id: 'b-tree', name: 'B-Tree', description: 'Self-balancing tree for disk-based storage', category: 'database', difficulty: 3, importance: 0.7, interviewFrequency: 0.5, prerequisites: ['bst', 'indexing'], relatedConcepts: ['lsm-tree', 'indexing'] },

  { id: 'gc', name: 'Garbage Collection', description: 'Automatic memory reclamation', category: 'os', difficulty: 3, importance: 0.6, interviewFrequency: 0.6, prerequisites: ['memory-management'], relatedConcepts: ['jvm-memory', 'mark-sweep', 'generational-gc'], visualType: 'graph', defaultAnimation: 'flow' },
  { id: 'jvm-memory', name: 'JVM Memory Model', description: 'Heap, stack, method area, metaspace', category: 'os', difficulty: 3, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['memory-management'], relatedConcepts: ['gc', 'class-loading'], visualType: 'graph', defaultAnimation: 'flow' },
  { id: 'memory-management', name: 'Memory Management', description: 'Allocation and deallocation of memory', category: 'os', difficulty: 2, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['os-processes'], relatedConcepts: ['gc', 'virtual-memory', 'segmentation'] },
  { id: 'os-processes', name: 'OS Processes', description: 'Process lifecycle, scheduling, context switching', category: 'os', difficulty: 2, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['computer-basics'], relatedConcepts: ['threads', 'scheduling-algorithms'] },
  { id: 'virtual-memory', name: 'Virtual Memory', description: 'Paging, page tables, TLB, swapping', category: 'os', difficulty: 3, importance: 0.6, interviewFrequency: 0.5, prerequisites: ['memory-management'], relatedConcepts: ['paging', 'mmu'] },
  { id: 'scheduling-algorithms', name: 'CPU Scheduling', description: 'Round robin, priority, multi-level feedback queue', category: 'os', difficulty: 2, importance: 0.6, interviewFrequency: 0.5, prerequisites: ['os-processes'], relatedConcepts: ['thread-pool', 'real-time-os'] },

  { id: 'jvm-classloading', name: 'Class Loading', description: 'Load, link, initialize Java classes', category: 'language', difficulty: 3, importance: 0.4, interviewFrequency: 0.4, prerequisites: ['jvm-memory'], relatedConcepts: ['jvm-memory', 'reflection'] },
  { id: 'python-gil', name: 'Python GIL', description: 'Global interpreter lock limiting parallelism', category: 'language', difficulty: 2, importance: 0.5, interviewFrequency: 0.5, prerequisites: ['threads', 'concurrency-basics'], relatedConcepts: ['multiprocessing', 'asyncio'] },
  { id: 'async-await', name: 'Async/Await', description: 'Coroutine-based async programming model', category: 'language', difficulty: 2, importance: 0.7, interviewFrequency: 0.7, prerequisites: ['event-loop', 'callbacks'], relatedConcepts: ['promises', 'reactive-programming'] },
  { id: 'event-loop', name: 'Event Loop', description: 'Single-threaded concurrency for I/O tasks', category: 'language', difficulty: 2, importance: 0.7, interviewFrequency: 0.6, prerequisites: ['async-await'], relatedConcepts: ['nodejs-architecture', 'reactor-pattern'] },

  { id: 'tensor-operations', name: 'Tensor Operations', description: 'Multi-dimensional array computations for ML', category: 'ai', difficulty: 3, importance: 0.7, interviewFrequency: 0.4, prerequisites: ['linear-algebra-basics'], relatedConcepts: ['neural-networks', 'gpu-computing'], visualType: 'tensor' },
  { id: 'neural-networks', name: 'Neural Networks', description: 'Layered computation graphs for learning', category: 'ai', difficulty: 3, importance: 0.8, interviewFrequency: 0.5, prerequisites: ['tensor-operations', 'calculus-basics'], relatedConcepts: ['backpropagation', 'cnn', 'rnn'], visualType: 'graph', defaultAnimation: 'flow' },
  { id: 'backpropagation', name: 'Backpropagation', description: 'Gradient computation via chain rule', category: 'ai', difficulty: 4, importance: 0.7, interviewFrequency: 0.4, prerequisites: ['neural-networks', 'calculus-basics'], relatedConcepts: ['gradient-descent', 'autograd'] },
  { id: 'transformers', name: 'Transformers', description: 'Attention-based architecture for sequence modeling', category: 'ai', difficulty: 4, importance: 0.9, interviewFrequency: 0.6, prerequisites: ['neural-networks', 'attention-mechanism'], relatedConcepts: ['bert', 'gpt', 'self-attention'], visualType: 'graph', defaultAnimation: 'flow' },
]

export const CONCEPT_RELATIONSHIPS: [string, string, RelType][] = [
  ['arrays', 'linked-list', 'related-to'],
  ['arrays', 'dynamic-array', 'related-to'],
  ['arrays', 'bubble-sort', 'prerequisite'],
  ['arrays', 'binary-search', 'prerequisite'],
  ['arrays', 'insertion-sort', 'prerequisite'],
  ['arrays', 'two-pointers', 'prerequisite'],
  ['linked-list', 'queue', 'prerequisite'],
  ['linked-list', 'stack', 'related-to'],
  ['heap', 'priority-queue', 'implementation-of'],
  ['binary-tree', 'bst', 'prerequisite'],
  ['bst', 'avl-tree', 'variant-of'],
  ['bst', 'red-black-tree', 'variant-of'],
  ['bst', 'b-tree', 'related-to'],
  ['recursion', 'dfs', 'prerequisite'],
  ['recursion', 'backtracking', 'prerequisite'],
  ['recursion', 'dynamic-programming', 'prerequisite'],
  ['recursion', 'divide-and-conquer', 'prerequisite'],
  ['recursion', 'tree-traversal', 'prerequisite'],
  ['bubble-sort', 'insertion-sort', 'related-to'],
  ['bubble-sort', 'quick-sort', 'prerequisite'],
  ['bubble-sort', 'selection-sort', 'related-to'],
  ['quick-sort', 'merge-sort', 'related-to'],
  ['dfs', 'bfs', 'related-to'],
  ['bfs', 'dijkstra', 'prerequisite'],
  ['dijkstra', 'a-star', 'variant-of'],
  ['bfs', 'shortest-path', 'implementation-of'],
  ['hash-map', 'hash-set', 'implementation-of'],
  ['hash-map', 'consistent-hashing', 'prerequisite'],
  ['two-pointers', 'sliding-window', 'prerequisite'],
  ['dynamic-programming', 'greedy-algorithms', 'related-to'],
  ['distributed-systems', 'raft', 'prerequisite'],
  ['distributed-systems', 'kafka', 'prerequisite'],
  ['distributed-systems', 'cap-theorem', 'related-to'],
  ['distributed-systems', 'microservices', 'prerequisite'],
  ['raft', 'paxos', 'related-to'],
  ['raft', 'kafka', 'related-to'],
  ['threads', 'mutex', 'prerequisite'],
  ['mutex', 'deadlock', 'prerequisite'],
  ['mutex', 'semaphore', 'related-to'],
  ['deadlock', 'race-condition', 'related-to'],
  ['mutex', 'synchronization', 'implementation-of'],
  ['threads', 'thread-pool', 'related-to'],
  ['mutex', 'atomic-operations', 'related-to'],
  ['sql-basics', 'indexing', 'prerequisite'],
  ['sql-basics', 'transactions', 'prerequisite'],
  ['sql-basics', 'nosql', 'related-to'],
  ['indexing', 'b-tree', 'implementation-of'],
  ['tcp-ip', 'tcp-handshake', 'prerequisite'],
  ['tcp-ip', 'http', 'prerequisite'],
  ['http', 'api-design', 'prerequisite'],
  ['dns', 'cdn', 'prerequisite'],
  ['os-processes', 'threads', 'prerequisite'],
  ['memory-management', 'gc', 'prerequisite'],
  ['memory-management', 'jvm-memory', 'prerequisite'],
  ['gc', 'jvm-memory', 'related-to'],
  ['os-processes', 'scheduling-algorithms', 'related-to'],
  ['threads', 'python-gil', 'related-to'],
  ['async-await', 'event-loop', 'implementation-of'],
  ['tensor-operations', 'neural-networks', 'prerequisite'],
  ['neural-networks', 'backpropagation', 'prerequisite'],
  ['neural-networks', 'transformers', 'prerequisite'],
  ['kafka', 'publish-subscribe', 'implementation-of'],
  ['caching', 'cache-eviction', 'related-to'],
  ['database-design', 'sharding', 'related-to'],
  ['hash-map', 'kafka-partitioning', 'prerequisite'],
  ['sharding', 'consistent-hashing', 'related-to'],
]

export function buildDefaultKnowledgeGraph(): { nodes: KnowledgeNode[]; edges: KnowledgeEdge[] } {
  const edges: KnowledgeEdge[] = CONCEPT_RELATIONSHIPS.map(([from, to, type]) => ({ from, to, type }))
  return { nodes: DEFAULT_CONCEPT_GRAPH, edges }
}
