export { createFrame, createVariableState, createHeapObject, diffVariables } from './Frame'
export type { ExecutionFrame, VariableState, HeapObject, VariableDiff } from './Frame'
export { TraceRecorder } from './TraceRecorder'
export type { ExecutionTrace, ExecutionSnapshot } from './TraceRecorder'
export { TraceReplay } from './TraceReplay'
export { StateReconstructor } from './StateReconstructor'
export type { ReconstructedState } from './StateReconstructor'
export { TraceCompressor } from './TraceCompressor'
export type { DeltaFrame, DeltaEncodedTrace, CompressedEvent } from './TraceCompressor'
export { ProxyTracker } from './instrumentation/ProxyTracker'
export { RuntimeHooks } from './instrumentation/RuntimeHooks'
export { MemoryGraph } from './memory/MemoryGraph'
export type { HeapDiff } from './memory/MemoryGraph'
